name: CI
on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Scala with JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 21
        check-latest: true
        cache: sbt

    - name: Build and Test
      run: sbt -v +test
