name: CI
on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          java-version: "adopt@1.14"
      - uses: olafurpg/setup-scala@v13
      - run: sbt -v +test
